from gracy.exceptions import GracyException

DatatimesError = GracyException
